sudo: required
services:
  - docker

before_install:
  - docker build -t gravboy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gravboy/react-test npm test

after_success:
  - docker build -t gravboy/multi-client ./client
  - docker build -t gravboy/multi-nginx ./nginx
  - docker build -t gravboy/multi-server ./server
  - docker build -t gravboy/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push gravboy/multi-client
  - docker push gravboy/multi-nginx
  - docker push gravboy/multi-server
  - docker push gravboy/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker3"
  env: "Multidocker3-env"
  bucket_name: "elasticbeanstalk-us-east-2-029015861344"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
